### PR TITLE
fix: further cleanup agave

### PR DESCRIPTION
**Pull request by akshaynexus**
just cleanup code and log data better

### CODE REVIEW

**Comment by akshaynexus** [comment]
looks like actions is not working well,will check and fix that shortly @SunWeb3Sec

**Comment by SunWeb3Sec** [comment]
@akshaynexus 
Please fix command in ci. Thanks a lot!
Error:
fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:

**Comment by akshaynexus** [comment]
@SunWeb3Sec Check pr #588  and merge it ,then run the action again

**Comment by akshaynexus** [comment]
@SunWeb3Sec  The CI Test passes now should be good to go for future PRS to auto test and see if tests pass for new changes of any _exp.sol file

**Comment by SunWeb3Sec** [comment]
Super! Thanks @akshaynexus

**Pull request merged**
